openapi: 3.0.2
info:
  title: employeeEngagementPlatform
  version: 1.0.0
paths:
  /hours:
    post:
      summary: create new hours
      tags: [Hours]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hours'
      responses:
        '201':
          description: hours added
        '400':
          description: if requests body does not contain required fields or required fields are invalid format
    get:
      summary: Returns list of hours
      tags: [Hours]
      responses:
        200:
          description: list of the hours
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/hours' 

  /hours/{id}:
    patch:
      summary: update hours
      security:
        - bearerAuth: []
      tags: [Hours]
      parameters:
        - in: path
          name: id
          schema:
           type: string
          required: true
          description: ID of the hour
          example: 636a228c62df96c5baaec96a
      requestBody:
          required: true
          content:
            application/json:
              schema:
                type: ovject
                properties:
                  userId: string
                  month: string
                  year: number
                  days:
                    day: string
                    hours: number
              example:
                    _id: 636a228c62df96c5baaec969
                    userId: 6367edbf8901c69da661f0b9
                    month: March
                    year: 2011
                    days:   
                      createdAt: 2022-11-08T09:23:38.336Z
                      day: 25
                      hours: 7
                      _id: 636a228c62df96c5baaec96a      
      responses:
        "201":
          description: patches hours by id
        '400':
          description: if requests body does not contain required fields or required fields are invalid format
    delete:
      summary: deletes hours from db
      security:
        - bearerAuth: []
      tags: [Hours]
      parameters:
        - in: path
          name: id
          schema:
           type: string
          required: true
      responses:
        "200":
            description: string id of hour deleted
components:
  schemas:
    hours:
      title: Root Type for employees
      description: ''
      type: array
      items:
        $ref: '#/components/schemas/hours'
      example:
        _id: 636a228c62df96c5baaec969
        userId:
          - 6366eec1385c79a791f80ee9
        month: November
        year: 2009
        days:
          day: wednesday
          hours: 9 
